/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionDialog: typeof import('./src/components/common/ActionDialog.vue')['default']
    ActionFeedback: typeof import('./src/components/common/ActionFeedback.vue')['default']
    AnnouncementsInterface: typeof import('./src/components/interfaces/AnnouncementsInterface.vue')['default']
    ConfirmCancel: typeof import('./src/components/common/ConfirmCancel.vue')['default']
    ConfirmDelete: typeof import('./src/components/common/ConfirmDelete.vue')['default']
    ContentLoading: typeof import('./src/components/common/ContentLoading.vue')['default']
    CrudForm: typeof import('./src/components/crud/CrudForm.vue')['default']
    CrudInterface: typeof import('./src/components/interfaces/CrudInterface.vue')['default']
    CrudList: typeof import('./src/components/crud/CrudList.vue')['default']
    DashboardCard: typeof import('./src/components/dashboard/DashboardCard.vue')['default']
    DashboardTotalRequestCount: typeof import('./src/components/dashboard/DashboardTotalRequestCount.vue')['default']
    DashboardTotalRequestDuration: typeof import('./src/components/dashboard/DashboardTotalRequestDuration.vue')['default']
    DashboardTotalSessionCount: typeof import('./src/components/dashboard/DashboardTotalSessionCount.vue')['default']
    LayoutCenter: typeof import('./src/components/common/LayoutCenter.vue')['default']
    ModelAuditor: typeof import('./src/components/common/ModelAuditor.vue')['default']
    OverlayAnnouncements: typeof import('./src/components/overlay/OverlayAnnouncements.vue')['default']
    OverlayAppBar: typeof import('./src/components/overlay/OverlayAppBar.vue')['default']
    OverlayChangePassword: typeof import('./src/components/overlay/OverlayChangePassword.vue')['default']
    OverlayNavigationDrawer: typeof import('./src/components/overlay/OverlayNavigationDrawer.vue')['default']
    OverlayUserMenu: typeof import('./src/components/overlay/OverlayUserMenu.vue')['default']
    RolesInterface: typeof import('./src/components/interfaces/RolesInterface.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerError: typeof import('./src/components/common/ServerError.vue')['default']
    UsersInterface: typeof import('./src/components/interfaces/UsersInterface.vue')['default']
  }
}
